baseURL = 'https://rafuaero.github.io/'
languageCode = 'pt-BR'
title = 'costacurta.me'
theme = 'mini'


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[services]
  [services.googleAnalytics]
    ID = 'G-287QNEHVGP'


