baseURL = 'https://rafuaero.github.io/'
languageCode = 'pt-BR'
title = 'costacurta.me'
theme = 'mini'

[params]
	subtitle = 'aventuras em hugo'

[taxonomies]
  category = "categories"
  tag = 'tags'

sectionPagesMenu = 'main'


# essa config é para merge as configurações aqui e do tema
  _merge = 'shallow'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[services]
  [services.googleAnalytics]
    ID = 'G-287QNEHVGP'


googleAnalytics = 'G-287QNEHVGP'

