baseURL = 'https://rafuaero.github.io/'
languageCode = 'pt-BR'
title = 'costacurta.me'
theme = 'archie'

[params]
	subtitle = 'aventuras em hugo'

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "outros"
  url = "/outros"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

  [[menu.main]]
  name = "sobre"
  url = "/about"
  weight = 5

  

# sectionPagesMenu = 'main'


# essa config é para merge as configurações aqui e do tema
  _merge = 'shallow'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[services]
  [services.googleAnalytics]
    ID = 'G-287QNEHVGP'


googleAnalytics = 'G-287QNEHVGP'

